### ISSUE TITLE
Could you share the script of getting the models which named model-stage2.pb and model-stage1.pd？

### ISSUE THREAD

**Issue by liyi522** [maups/ear-recognition#1]
Hi！ I'm very interested in your great work. And I have read your article. I recently worked on the landmarks detection of ears and the landmarks of your work are not suitable for my work. I also want to learn the method of CNN. So I would appreciate you if you could share the code of the process for getting the models which named model-stage2.pb and model-stage1.pd. Looking forward to your reply.

**Comment by maups** [comment]
Unfortunately, I don't have time to organize and put the training code in here any time soon. I'll try to work on it at the end of the year. Hope it is not too late.

**Comment by liyi522** [comment]
Thank you all the same. I'll try something else.
